###
GET http://localhost:3000/paises

### //este falla
GET http://localhost:3000/paises/2

###
POST http://localhost:3000/paises
Content-Type: application/json
 
{
    "pais": "Rusia",
    "capital": "Moscú",
    "poblacion":200000000,
    "moneda": "Rublo Ruso",
    "continente":"Europa y Asia"
}

### 
DELETE http://localhost:3000/paises/2


###
PUT http://localhost:3000/paises/3
Content-Type: application/json

{
   "moneda":"Dolar Canadiense."
}

